// Generated by CoffeeScript 1.7.1
(function() {
  require.config({
    baseUrl: "js/libs/",
    paths: {
      "jquery": "jquery-2.1.0.min",
      "bootstrap": "bootstrap.min",
      "troen-scene": "../troen-scene",
      "trackballcontrols": "trackballcontrols",
      "lightbox": "lightbox-2.6.min"
    },
    shim: {
      "bootstrap": {
        deps: ["jquery"]
      },
      "lodash": {
        exports: "_"
      },
      "three": {
        exports: "THREE"
      },
      "trackballcontrols": {
        deps: ["three"]
      },
      "lightbox": {
        deps: ["jquery"]
      }
    }
  });

  require(["troen-scene", "lodash", "jquery", "bootstrap", "lightbox"], function(TroenScene) {
    var scrollToDownload, scrollToTop, troenScene;
    console.log(THREE);
    troenScene = void 0;
    $("#cycle-tab").one("shown.bs.tab", function(evt) {
      evt.preventDefault();
      if (!troenScene) {
        return troenScene = new TroenScene();
      }
    });
    scrollToDownload = function() {
      var aTag;
      aTag = $("#download");
      return $('html,body').animate({
        scrollTop: aTag.offset().top
      }, 'slow');
    };
    scrollToTop = function() {
      return $('html,body').animate({
        scrollTop: 0
      }, 'slow');
    };
    $("#download-tab").click(function() {
      if (!$("#home.active").length) {
        $("#home-tab").tab("show");
        return $("#home-tab").one("shown.bs.tab", scrollToDownload);
      } else {
        return scrollToDownload();
      }
    });
    return $("#home-tab").click(scrollToTop);
  });

}).call(this);

//# sourceMappingURL=main.map
